- name: Install Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

- name: Enable and Install Redis 6.2 from package streams.
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: installed

- name: Update listner Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes