- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download and unzip the content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

## Download from nexus
- name: Download and extract the {{ component }} content from nexus
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.devopsb71.live:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes

- name: Create nginx config in nginx file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Create roboshop config in nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
