- name: Prometheus Config Update
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Alert rules Config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
    loop: "{{ alert_files }}"

- name: Restart Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted