- name: Set hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: load exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: exporter
  when: node_exporter

- name: Install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
  when: filebeat