if [ "${schema_type}" == "mongo" ]; then
    print_head "copy mongodb repo"
    cp ${code_dir}/Config/mongodb.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
    status_check $?

    print_head "install mongodb"
    yum install mongodb-org-shell -y &>>${log_file}
    status_check $?

    print_head "load mongo schema"
    mongo --host mongodb.devopsb71.live </app/schema/${component}.js &>>${log_file}
    status_check $?
    elif [ "${schema_type}" == "mysql" ]; then
    print_head "install mysql client"
    yum install mysql -y &>>${log_file}
    status_check $?

    print_head "load mysql schema"
    mysql -h mysql.devopsb71.live -uroot -p${mysql_root_passwd} < /app/schema/shipping.sql  &>>${log_file}
    status_check $?
    fi
 }

