groups:
  - name: roboshop
    rules:
      - alert: ServerDown
        expr: up < 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Server Down

      - alert: High CPU Usage
        expr: up < 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High CPU Usage