groups:
  - name: roboshop-service-alerts
    rules:
      - alert: Service Down Alert - cart service
        expr: node_systemd_unit_state{exported_name="cart.service", state="active"}
        for: 30s
        labels:
          severity: critical
          appName: cart
        annotations:
          summary: Service Down on server - service name - cart.service