groups:
  - name: roboshop-service-alerts
    rules:
    {% for component in components %}

      - alert: Service Down Alert - {{ component.name }} service
        expr: node_systemd_unit_state{exported_name="{{ component.service_name }}.service", state="active"}
        for: 30s
        labels:
          severity: critical
          appName: {{ component.name }}
        annotations:
          summary: Service Down on server {{ component.name }} - service name - {{ component.service_name }}.service

    {% endfor %}